// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten

package com.consumimurigni.stellarj.scp.xdr;


import java.io.IOException;

import com.consuminurigni.stellarj.xdr.XdrDataInputStream;
import com.consuminurigni.stellarj.xdr.XdrDataOutputStream;

// === xdr source ============================================================

//  typedef opaque Signature<64>;

//  ===========================================================================
public class Signature  {
  private byte[] Signature;
  public byte[] getSignature() {
    return this.Signature;
  }
  public void setSignature(byte[] value) {
    this.Signature = value;
  }
  public static void encode(XdrDataOutputStream stream, Signature  encodedSignature) throws IOException {
  int Signaturesize = encodedSignature.Signature.length;
  stream.writeInt(Signaturesize);
  stream.write(encodedSignature.getSignature(), 0, Signaturesize);
  }
  public static Signature decode(XdrDataInputStream stream) throws IOException {
    Signature decodedSignature = new Signature();
  int Signaturesize = stream.readInt();
  decodedSignature.Signature = new byte[Signaturesize];
  stream.read(decodedSignature.Signature, 0, Signaturesize);
    return decodedSignature;
  }
}
