// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten

package com.consuminurigni.stellarj.xdr;


import java.io.IOException;

// === xdr source ============================================================

//  typedef unsigned int uint32;

//  ===========================================================================
public class Uint32 extends XdrInteger {
  public static final Uint32 ZERO = null;
public static final Uint32 ONE = null;
public static final Uint32 UINT32_MAX = null;
private Integer uint32;
  public Uint32(int i) {
	  uint32 = i;
}
public Uint32() {
	// TODO Auto-generated constructor stub
}
public Integer getUint32() {
    return this.uint32;
  }
  public void setUint32(Integer value) {
    this.uint32 = value;
  }
  public static void encode(XdrDataOutputStream stream, Uint32  encodedUint32) throws IOException {
  stream.writeInt(encodedUint32.uint32);
  }
  public static Uint32 decode(XdrDataInputStream stream) throws IOException {
    Uint32 decodedUint32 = new Uint32();
  decodedUint32.uint32 = stream.readInt();
    return decodedUint32;
  }
public byte[] toOpaque() {
	// TODO Auto-generated method stub
	return null;
}
public boolean eq(int i) {
	// TODO Auto-generated method stub
	return false;
}
public boolean eq(Uint32 nPrepared) {
	// TODO Auto-generated method stub
	return false;
}
public boolean lt(Uint32 nh) {
	// TODO Auto-generated method stub
	return false;
}
public boolean gt(int i) {
	// TODO Auto-generated method stub
	return false;
}
public boolean lteq(Uint32 counter) {
	// TODO Auto-generated method stub
	return false;
}
public boolean neq(int i) {
	// TODO Auto-generated method stub
	return false;
}
public boolean gteq(Uint32 nh) {
	// TODO Auto-generated method stub
	return false;
}
public Uint32 plus(int i) {
	// TODO Auto-generated method stub
	return null;
}
public boolean gt(Uint32 low) {
	// TODO Auto-generated method stub
	return false;
}
public boolean neq(Uint32 uint32Max) {
	// TODO Auto-generated method stub
	return false;
}
}
