// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten

package com.consuminurigni.stellarj.xdr;


import java.io.IOException;


// === xdr source ============================================================

//  typedef opaque Value<>;

//  ===========================================================================
public class Value  {
  public static final Value NO_VALUE = null;//?? empty @see BallotProtocol
  /*
   * if (newHfound)
	    {
	        SCPBallot newC = new SCPBallot(Uint32.ZERO, Value.NO_VALUE);///!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	        // now, look for newC (left as 0 if no update)
	        // step (3) from the paper
   */
private byte[] Value;
  public byte[] getValue() {
    return this.Value;
  }
  public void setValue(byte[] value) {
    this.Value = value;
  }
  public static void encode(XdrDataOutputStream stream, Value  encodedValue) throws IOException {
  int Valuesize = encodedValue.Value.length;
  stream.writeInt(Valuesize);
  stream.write(encodedValue.getValue(), 0, Valuesize);
  }
  public static Value decode(XdrDataInputStream stream) throws IOException {
    Value decodedValue = new Value();
  int Valuesize = stream.readInt();
  decodedValue.Value = new byte[Valuesize];
  stream.read(decodedValue.Value, 0, Valuesize);
    return decodedValue;
  }
public boolean isEmpty() {
	// TODO Auto-generated method stub
	return false;
}
public boolean lt(Value value2) {
	// TODO Auto-generated method stub
	return false;
}
public boolean eq(Value value2) {
	// TODO Auto-generated method stub
	return false;
}
public void clear() {
	// TODO Auto-generated method stub
	
}
public static Value decode(byte[] encode) {
	// TODO Auto-generated method stub
	return null;
}
public int size() {
	// TODO Auto-generated method stub
	return 0;
}
}
