// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten

package com.consuminurigni.stellarj.scp.xdr;


import java.io.IOException;

import com.consuminurigni.stellarj.xdr.Hash;
import com.consuminurigni.stellarj.xdr.Value;
import com.consuminurigni.stellarj.xdr.XdrDataInputStream;
import com.consuminurigni.stellarj.xdr.XdrDataOutputStream;

// === xdr source ============================================================

//  struct SCPNomination
//  {
//      Hash quorumSetHash; // D
//      Value votes<>;      // X
//      Value accepted<>;   // Y
//  };

//  ===========================================================================
public class SCPNomination  {
  public SCPNomination () {}
  private Hash quorumSetHash;
  public Hash getQuorumSetHash() {
    return this.quorumSetHash;
  }
  public void setQuorumSetHash(Hash value) {
    this.quorumSetHash = value;
  }
  private Value[] votes;
  public ValueSet getVotes() {
	  return null;
  }
  public Value[] _getVotes() {
    return this.votes;
  }
  public void setVotes(Value[] value) {
    this.votes = value;
  }
  private Value[] accepted;
  public ValueSet getAccepted() {
	  return null;
  }
  public Value[] _getAccepted() {
    return this.accepted;
  }
  public void setAccepted(Value[] value) {
    this.accepted = value;
  }
  public static void encode(XdrDataOutputStream stream, SCPNomination encodedSCPNomination) throws IOException{
    Hash.encode(stream, encodedSCPNomination.quorumSetHash);
    int votessize = encodedSCPNomination._getVotes().length;
    stream.writeInt(votessize);
    for (int i = 0; i < votessize; i++) {
      Value.encode(stream, encodedSCPNomination.votes[i]);
    }
    int acceptedsize = encodedSCPNomination._getAccepted().length;
    stream.writeInt(acceptedsize);
    for (int i = 0; i < acceptedsize; i++) {
      Value.encode(stream, encodedSCPNomination.accepted[i]);
    }
  }
  public static SCPNomination decode(XdrDataInputStream stream) throws IOException {
    SCPNomination decodedSCPNomination = new SCPNomination();
    decodedSCPNomination.quorumSetHash = Hash.decode(stream);
    int votessize = stream.readInt();
    decodedSCPNomination.votes = new Value[votessize];
    for (int i = 0; i < votessize; i++) {
      decodedSCPNomination.votes[i] = Value.decode(stream);
    }
    int acceptedsize = stream.readInt();
    decodedSCPNomination.accepted = new Value[acceptedsize];
    for (int i = 0; i < acceptedsize; i++) {
      decodedSCPNomination.accepted[i] = Value.decode(stream);
    }
    return decodedSCPNomination;
  }
public int getNumAccepted() {
	// TODO Auto-generated method stub
	return 0;
}
public int getNumVotes() {
	// TODO Auto-generated method stub
	return 0;
}
public void addVote(Value v) {
	// TODO Auto-generated method stub
	
}
public void addAccepted(Value a) {
	// TODO Auto-generated method stub
	
}
}
